// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNKvLXCfqSlTP2MJ8ZNKlVdsJiWLyHDYA',
    appId: '1:302879428294:android:ce324371fe250c93bdd1c7',
    messagingSenderId: '302879428294',
    projectId: 'foodapp-b4869',
    databaseURL: 'https://foodapp-b4869-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-b4869.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWxB_sogC8q1_s6ygK12DEERPTrqwioH4',
    appId: '1:302879428294:ios:4ef02a53963f23d1bdd1c7',
    messagingSenderId: '302879428294',
    projectId: 'foodapp-b4869',
    databaseURL: 'https://foodapp-b4869-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-b4869.appspot.com',
    iosClientId: '302879428294-41j5i22936u9ihkqe9omdq45m9hf19dd.apps.googleusercontent.com',
    iosBundleId: 'com.example.iraApp',
  );
}
